### ISSUE TITLE
[Bug]: Game crash when Shift-Crafting.

### ISSUE THREAD

**Issue by malte9799** [mrshmllow/BetterRecipeBook#102]
### What happened?

A bug happened!

WHY RELEASE A NEW VERSION WHEN ITS NOT TESTET PROPERLLY AND CRASHES THE GAME ALL THE TIME????!!

### Modloader

Fabric (Default)

### Minecraft Version

1.20.2

### Mod Version

rc2

### Relevant log output

```shell
.
```

**Comment by mrshmllow** [comment]
try again.
