### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by viktordimov** [mrshmllow/BetterRecipeBook#129]
Search items based on namespace/mod 
Example:
`@minecraft` will show vanilla items only
`@techreborn` will show tech reborn only
`@adastra` etc...

**Comment by mrshmllow** [comment]
Use `ID:` not `@ID`

![image](https://github.com/mrshmllow/BetterRecipeBook/assets/40532058/a4dddcb7-8a98-4883-b945-f1b7b171c319)
![image](https://github.com/mrshmllow/BetterRecipeBook/assets/40532058/e6806173-d3b5-4f29-9be4-b37eb7b86c11)

**Comment by mrshmllow** [comment]
Duplicate of #78
