### ISSUE TITLE
make 1.21

### ISSUE THREAD

**Issue by Legendmanj** [mrshmllow/BetterRecipeBook#143]
Update to 1.21, thank you

**Comment by mrshmllow** [comment]
Hey, I'm a bit confused. Versions for 1.21 are already out.

**Comment by Legendmanj** [comment]
> Hey, I'm a bit confused. Versions for 1.21 are already out.

not on modrinth i suppose

**Comment by mrshmllow** [comment]
Are you filtering by Forge?

![Screenshot_20240710-143741](https://github.com/mrshmllow/BetterRecipeBook/assets/40532058/ebd3f9ea-e087-454d-9934-93e44eb09199)

**Comment by Legendmanj** [comment]
> Are you filtering by Forge?
> 
> ![Screenshot_20240710-143741](https://private-user-images.githubusercontent.com/40532058/347258734-ebd3f9ea-e087-454d-9934-93e44eb09199.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2MDc1MjUsIm5iZiI6MTcyMDYwNzIyNSwicGF0aCI6Ii80MDUzMjA1OC8zNDcyNTg3MzQtZWJkM2Y5ZWEtZTA4Ny00NTRkLTk5MzQtOTNlNDRlYjA5MTk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEwVDEwMjcwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxZmI3ZmNiOWYxZDIyMGNmMzdiMDgzMjljYmVkZjk2ZjQ3MjBkZTg4MzI2MTQ0ZTMyMDk3MjVhNWQ1NmZlY2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TV0V-cKmJ_x8XYgBXkaVRDO8BySp9-O96TetPNzi-2A)

really sorry for the confusing i have done here, mate! Seems that i didn't see all the version given, which has 1.21 mentioned
![image](https://github.com/mrshmllow/BetterRecipeBook/assets/124070423/01432405-0189-4bd2-8b54-8574d45388e3)
tbh i don't normally see all the version present as almost all the mods i have known from modrinth seem to have their latest version mentioned on the featured versions, but thank you for clarifying my mistake lmao (;
