### ISSUE TITLE
Allow potion effect statuses to be shown when interacting with brewing stands

### ISSUE THREAD

**Issue by Kichura** [mrshmllow/BetterRecipeBook#18]
When interacting with brewing stands, the potion effects are completely hidden instead of being shown just like the normal inventory containers.

So my suggestion was to allow the player to see the potion effects instead of just hiding them entirely.

Brewing Stand:
![image](https://user-images.githubusercontent.com/68134602/137587267-712b26bc-b9cb-4f3e-bf00-ace49953695d.png)

Inventory:
![image](https://user-images.githubusercontent.com/68134602/137587281-2f3a85e5-4d5f-4b18-9d1e-4c97b4b7465f.png)

**Comment by mrshmllow** [comment]
From what i remember, they only show in your inventory. Changing that is out of the scope for this mod
