### ISSUE TITLE
Scroll in circles with no recipes

### ISSUE THREAD

**Issue by Moonyol** [mrshmllow/BetterRecipeBook#19]
If u turn on scroll in circles and have no recipes in ur book, u can do this by showing craftable only after u scroll ur game will crash if notenoughcrashes is installed after u log back into ur world all entities will be invisible

https://user-images.githubusercontent.com/92951072/138347380-89dacf51-ff9c-40ee-950e-3b4ce4ac00bf.mp4

**Comment by mrshmllow** [comment]
Let me know if you have any more troubles after this patch comes out
