### ISSUE TITLE
Ability to change key for featuring/pinning recipes

### ISSUE THREAD

**Issue by Disketaa** [mrshmllow/BetterRecipeBook#25]

**Comment by mrshmllow** [comment]
the reason that is isnt a thing yet is because minecraft keybinds dont work in a menu

**Comment by Atakku** [comment]
> the reason that is isnt a thing yet is because minecraft keybinds dont work in a menu

You can use F key in Minecraft to put an item into offhand when in a menu, and its configurable

**Comment by vos6434** [comment]
Any update on this?

**Comment by mrshmllow** [comment]
not really

**Comment by mrshmllow** [comment]
Idk why it took me almost 2 years but adding this in 1.10.0

**Comment by Disketaa** [comment]
Love it!
