### ISSUE TITLE
Game crashes when taking fuel from furnace

### ISSUE THREAD

**Issue by keatit71** [mrshmllow/BetterRecipeBook#28]
Tried game twice removing another mod but when i removed better recipe book it didn't crash.

https://crashy.net/panWZlY2oV0oGx6AsNJe
[crash-2021-12-13_16.44.08-client.txt](https://github.com/mrshmllow/BetterRecipeBook/files/7705522/crash-2021-12-13_16.44.08-client.txt)
[2021-12-13-7.log](https://github.com/mrshmllow/BetterRecipeBook/files/7705524/2021-12-13-7.log)

**Comment by mrshmllow** [comment]
I cannot manage to reproduce this

**Comment by keatit71** [comment]
i can give you a zip of my configs and mods if that helps?

**Comment by mrshmllow** [comment]
A video would help, if you can

**Comment by keatit71** [comment]
not much happens i just right click on the coal from the furnace to half it then the crash happens.

**Comment by keatit71** [comment]
https://user-images.githubusercontent.com/42551576/145894662-1b617860-ce50-489b-965d-9a751ef676e1.mp4

**Comment by mrshmllow** [comment]
Thats very interesting. I still cant seem to do it myself.. Your config/brb.toml file would be very useful

**Comment by keatit71** [comment]
[betterrecipebook.zip](https://github.com/mrshmllow/BetterRecipeBook/files/7707234/betterrecipebook.zip)

**Comment by mrshmllow** [comment]
Hey, maybe you can try turning off all other mods except brb and see if it changes anything

**Comment by keatit71** [comment]
just tried it with only brb and the mods it needs which are cloth config and fabric api still had the same crash.

[latest.log](https://github.com/mrshmllow/BetterRecipeBook/files/7711207/latest.log)

**Comment by keatit71** [comment]
This issue has been fixed with the latest version of the mod.
