### ISSUE TITLE
Missing recipes

### ISSUE THREAD

**Issue by celsiusqc** [mrshmllow/BetterRecipeBook#29]
The book seems to be missing a few recipes or not picking them all. Also please add search indexing like jei if possible. Here you can see in the screenshot that the weapons and tools are not showing
https://i.imgur.com/EJHZcjv.png

**Comment by mrshmllow** [comment]
Thanks for opening this here. Are you using forge or fabric?

**Comment by mrshmllow** [comment]
Embarrassingly, it took me a while to realize it too lol

Also, in the settings there is dark mode option!

And ill look into new search options

**Comment by celsiusqc** [comment]
> Human error, you cant make swords in a 2x2 :)

![image](https://user-images.githubusercontent.com/63996164/146123071-9450b788-d6d2-4169-be53-dbeb3052bbdb.png)
There as still some things missing, like netherite sword in this and also the modded netherite swords from advanced netherite are not there

**Comment by mrshmllow** [comment]
Again, you cannot make a netherite sword in a crafting table. I don't know about that mod though.

**Comment by SebastianD334** [comment]
The mod itself needs to have support for the recipe book, if I recall correctly, a recipe is always unlocked when you craft it, tho you can set conditions so it unlocks when you have a specific ingredient, but it’s not this mod’s responsibility to support every mod, that’s their own responsibility.
