### ISSUE TITLE
Crash a few seconds after opening a brewing stand menu

### ISSUE THREAD

**Issue by JumperCzech** [mrshmllow/BetterRecipeBook#3]
[latest.log](https://github.com/mrshmllow/BetterRecipeBook/files/7271775/latest.log)
using only betterrecipebook and dependencies

**Comment by keatit71** [comment]
yep having the same issue
![image](https://user-images.githubusercontent.com/42551576/135729935-d8718037-9f53-40f2-9606-1f685b57de91.png
[crash-2021-10-02_20.42.44-client.txt](https://github.com/mrshmllow/BetterRecipeBook/files/7272124/crash-2021-10-02_20.42.44-client.txt)
)

**Comment by Purpzie** [comment]
Can reproduce.

**Comment by mrshmllow** [comment]
I will check this out

**Comment by Purpzie** [comment]
Still experiencing this bug even with the new version unfortunately

**Comment by mrshmllow** [comment]
Log?
