### ISSUE TITLE
let book be open/closed per crafting type

### ISSUE THREAD

**Issue by robosoup2** [mrshmllow/BetterRecipeBook#30]
very cool mod :)
The worst thing about vanilla book is that when I leave the crafting table, the book stays open in my inventory screen. and when I close it there, I have to reopen it when I go back to a crafting table. Would it be possible to always remember how you left it for each crafting screen?
This issue would also be less annoying if the player at least had a shortcut key for opening/closing the book, instead of having to literally click it. but that's a less direct solution idk

**Comment by mrshmllow** [comment]
Closing in favor of #58
