### ISSUE TITLE
[Suggestion]

### ISSUE THREAD

**Issue by Taknax** [mrshmllow/BetterRecipeBook#33]
I saw a hide button function in the settings and have a super idea. To make this more survival, you could bind the recipe book button  to the knowledege book. This would give the ability to define a recipe for the knowledge book to activate the recipe book button. If Knowledge not in the inventory recipe book button is hidden. As a sideeffect you would make a useless item useful. This could be configurable as gamemode.  Maybe could called something like creative mode and survival mode?

**Comment by mrshmllow** [comment]
I do not understand what you mean

**Comment by Taknax** [comment]
Its my english sry. I try to make screenshots to explain better.
