### ISSUE TITLE
[CurseForge] Missing dependencies

### ISSUE THREAD

**Issue by thimblebird** [mrshmllow/BetterRecipeBook#35]
Hello 🐢

It'd be great if you'd add all dependencies on the CurseForge website so the launcher installs them automatically.

**Comment by mrshmllow** [comment]
is this a new thing because idk how to do that

**Comment by thimblebird** [comment]
https://www.curseforge.com/minecraft/mc-mods/brb/relations/dependencies

You can see them here; but I don't know how to add dependencies.

**Comment by mrshmllow** [comment]
This was fixed a while ago
