### ISSUE TITLE
[Request] Smithing Table Recipe Book

### ISSUE THREAD

**Issue by Estrelaura** [mrshmllow/BetterRecipeBook#37]
Regarding Vanilla, a Smithing Table recipe book would be really good, specially for packs trying to not rely on JEI/REI. Support for the more famous modded workstations with a GUI would be good too, such as the Cooking Pot from Farmer's Delight.

**Comment by mrshmllow** [comment]
I certainly want to add the book to the smithing table after there are more than 1 recipe. I am very hesitant to add support for modded workstations because currently it requires a lot of manual work and there is no easy API like jei
