### ISSUE TITLE
"Could not execute entrypoint stage 'main' due to errors, provided by 'brb'!"

### ISSUE THREAD

**Issue by Laifsyn** [mrshmllow/BetterRecipeBook#38]
I'm not sure how to solve this issue or if it's some compatibility issue

<html>
<body>

[10:23:25] [main/FATAL]: Failed to start the minecraft server
--
481 | java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'brb'!
482 | at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.13.3.jar:?]
483 | at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.13.3.jar:?]
484 | at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.13.3.jar:?]
485 | at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.13.3.jar:?]
486 | at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.13.3.jar:?]
487 | at net.minecraft.server.Main.main(Main.java:106) [server-intermediary.jar:?]
488 | at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
489 | at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
490 | at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
491 | at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
492 | at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) [fabric-loader-0.13.3.jar:?]
493 | at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.13.3.jar:?]
494 | at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.13.3.jar:?]
495 | at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
496 | at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
497 | at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
498 | at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
499 | at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:66) [fabric-loader-0.13.3.jar:?]
500 | Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_746
501 | at marsh.town.brb.BetterRecipeBook.init(BetterRecipeBook.java:37) ~[brb-Fabric-1.5.6.jar:?]
502 | at marsh.town.brb.fabric.BetterRecipeBookFabric.onInitialize(BetterRecipeBookFabric.java:9) ~[brb-Fabric-1.5.6.jar:?]
503 | at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.13.3.jar:?]
504 | ... 15 more
505 | Caused by: java.lang.ClassNotFoundException: net.minecraft.class_746
506 | at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
507 | at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[?:?]
508 | at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
509 | at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:158) ~[fabric-loader-0.13.3.jar:?]
510 | at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
511 | at marsh.town.brb.BetterRecipeBook.init(BetterRecipeBook.java:37) ~[brb-Fabric-1.5.6.jar:?]
512 | at marsh.town.brb.fabric.BetterRecipeBookFabric.onInitialize(BetterRecipeBookFabric.java:9) ~[brb-Fabric-1.5.6.jar:?]
513 | at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.13.3.jar:?]
514 | ... 15 more

</body>
</html>

https://pastebin.com/4TEeTMwQ

**Comment by mrshmllow** [comment]
Try again without a billion mods

**Comment by mrshmllow** [comment]
Close due to inactivity
