### ISSUE TITLE
BetterRecipeBook crashes in 1.19.

### ISSUE THREAD

**Issue by Kichura** [mrshmllow/BetterRecipeBook#42]
When attempting to use inventories like creative mode, scrolling at all will cause the game to [crash](https://pastebin.com/raw/Jvh6bkN9).

**Comment by mrshmllow** [comment]
Can you provide a crash log?

**Comment by Kichura** [comment]
It is attached in the blue "crash" word.

**Comment by mrshmllow** [comment]
Im sorry but im having a really bad time trying to get IDEA to work on my system and its been on a lower priority I hope you understand

**Comment by mrshmllow** [comment]
Im going to try and setup codespaces

**Comment by mrshmllow** [comment]
The mod is now playable in both fabric and forge as of b17dbf2
