### ISSUE TITLE
The Button Does not fill the crating grid no matter how many times I press it

### ISSUE THREAD

**Issue by ardissaps** [mrshmllow/BetterRecipeBook#46]
It happen when all the ingerdient are match, if we have no ingredient it put the recipe on the grid.
(in short, in only give recipe if we don't have ingredient)
![image](https://user-images.githubusercontent.com/82106625/175799621-b9d209a1-c2eb-4595-9883-e7ae01191826.png)
https://paste.atlauncher.com/view/808cf51b-f18a-4253-83f8-98730e8408d8

**Comment by mrshmllow** [comment]
Does this happen for vanilla recipes?

**Comment by ardissaps** [comment]
> Does this happen for vanilla recipes?

Yes, only when we have the ingredient.

**Comment by mrshmllow** [comment]
Works for me

**Comment by ardissaps** [comment]
look like some mods causing it, but i don't know which, vanilla recipe book also does not work, sorry look like it is nothing to do with brb.

**Comment by Oyssis** [comment]
Happens to me

**Comment by Oyssis** [comment]
okay nvm he said it has nothing to do with brb

**Comment by ardissaps** [comment]
Yeah, it was bug on others mod but it is fixed, if I remember correctly from Roundaround Pick up Notification mod.

**Comment by Oyssis** [comment]
Weird I don't have that mod and that sometimes happens

**Comment by ardissaps** [comment]
You need to try disabling brb to see if it is fixed, for me problem persist so I guess not from brb.
