### ISSUE TITLE
Unlock all recipes option doesn't work

### ISSUE THREAD

**Issue by Oyssis** [mrshmllow/BetterRecipeBook#47]
Basically I turned on unlock all recipes and I didn't unlock

**Comment by mrshmllow** [comment]
Hello, it's on by default. Did you relogin to the world?

**Comment by Oyssis** [comment]
Yes I did

**Comment by Oyssis** [comment]
btw its a server does it matter?

**Comment by mrshmllow** [comment]
can you check it works for you out locally

**Comment by Oyssis** [comment]
it works now

**Comment by Oyssis** [comment]
only in single player it works
