### ISSUE TITLE
Brewing stand shows nothing in recipes

### ISSUE THREAD

**Issue by Oyssis** [mrshmllow/BetterRecipeBook#48]
if you search for something and then delete it you won't see any recipe
also if you click show all and then click again show brewings it also won't show any recipe

**Comment by mrshmllow** [comment]
can you provide your Minecraft log and I'll get on this

**Comment by Oyssis** [comment]
[latest.log](https://github.com/mrshmllow/BetterRecipeBook/files/9010599/latest.log)

**Comment by mrshmllow** [comment]
This is going to be real annoying to fix
