### ISSUE TITLE
Inventorio Compatibility

### ISSUE THREAD

**Issue by cawaulitra** [mrshmllow/BetterRecipeBook#49]
"Keep crafting screens centered" option makes recipe book offset too far from inventory and is not centered if Inventorio is installed.

Steps to reproduce:
1. Install "BetterRecipeBook", "Inventorio" and their dependencies.
2. Load up the world.
3. Make sure that "Keep crafting screens centered" set to true.
4. Open recipe book in inventory.

In-game screenshot:
![image](https://user-images.githubusercontent.com/39634179/176735969-19086a29-0374-4e48-b9b8-d1807bb69210.png)

Mods folder screenshot:
![image](https://user-images.githubusercontent.com/39634179/176736092-30026f88-ba99-4ee0-83a0-9195544f46b9.png)

**Comment by mrshmllow** [comment]
discussed in https://github.com/mrshmllow/BetterRecipeBook/pull/6. this is a mixin conflict and I feel that inventorio should fix it

**Comment by cawaulitra** [comment]
I've sent an issue to Inventorio dev. Thank you for responding.
