### ISSUE TITLE
Brewing stand recipe book is bugged

### ISSUE THREAD

**Issue by baobuh** [mrshmllow/BetterRecipeBook#51]
Splash potion recipes are in lingering potion's tab and vice versa and on clicking the recipes it looks messed up

**Comment by mrshmllow** [comment]
I know

**Comment by Anarasha** [comment]
<Technical information like Minecraft version and other mods at the bottom>

I love this mod, but I have an issue with the brewing stand. Sometimes it works, other times it shows up blank or shows only a small amount of potions. I have attached a screenshot where you can see it completely blank - and I made sure to have an Awkward Potion and Spider Eye in my inventory so I was for sure able to craft SOMETHING - even though the recipe book was set to display all. 
It seems to happen as a result of flipping on "Brewable", following which it will only show the potions you were able to brew at the time and it won't update again 

![bugscreenshot](https://user-images.githubusercontent.com/45836295/182030193-ddabccf4-e51a-4a16-9f0d-c7616d73fab2.jpg)

Minecraft version: Java 1.9
List of my other mods: 
Clumps 
Enchantment Descriptions
Jade
Just Enough Items 
Controlling
Fabric Waystones
Inventory Profiles Next 
Inventory Totem 
Iron Chests: Restocked 
Literally Chunk Loader 
Macaw's Bridges 
SlimeChunkF3
Speed Trading 
ToolTipFix
TrashSlot (Fabric Edition) 
Traveler's Backpack [Fabric]
Xaero's Minimap 
Xaero's World Map

**Comment by GuyInUniverse** [comment]
Having the same issue as above, toggling the show all button at the top right of the brewing recipe book will make all the recipes disappear. The only way I've been able to fix this is by never touching that button lol

**Comment by mrshmllow** [comment]
the original bug has been resolved

**Comment by mrshmllow** [comment]
i cannot reproduce the second unrelated bug, mods are not currently supported
