### ISSUE TITLE
Crashing on 1.19.2

### ISSUE THREAD

**Issue by ElMolgajete** [mrshmllow/BetterRecipeBook#61]
I've played with this mod before and its awesome, but when I try to play it on 1.19.2 Forge 43.2.6 it just crashes on startup leaving this screen
![image](https://user-images.githubusercontent.com/122349451/223667252-7bc0262a-27d0-431f-a5cd-1b446170f040.png)
Here's the crashlog: https://mclo.gs/OvQ25iI

**Comment by mrshmllow** [comment]
#57 duplicate
