### ISSUE TITLE
Brewing stand crash still not fixed

### ISSUE THREAD

**Issue by keatit71** [mrshmllow/BetterRecipeBook#7]
When changing pages on brewing stand the game still crashes.
[crash-2021-10-04_12.45.37-client.txt](https://github.com/mrshmllow/BetterRecipeBook/files/7277759/crash-2021-10-04_12.45.37-client.txt)

[latest.log](https://github.com/mrshmllow/BetterRecipeBook/files/7277761/latest.log)

**Comment by mrshmllow** [comment]
changing pages~ different crash ig. From what I can see the second log doesn't seem to have anything to do with this mod. Please disable all other mods and give me a more specific description to help reproduce.
Inside your Minecraft install, there should be a `brb.pins` file, what does it contain?

**Comment by keatit71** [comment]
Dont have any brb.pins file and still crashes only with your mod and its requirements. When i open the brewing stand i changes the pages in the recipe book and that causes the crash.
[latest.log](https://github.com/mrshmllow/BetterRecipeBook/files/7278023/latest.log)

**Comment by JumperCzech** [comment]
Still having the issue, game just crashes a few second after opening brewing stand, didn't click anything or even move my mouse.

Log: https://paste.ee/p/7yzGz

**Comment by mrshmllow** [comment]
Do you use the narrator? I think thats what is causing this

**Comment by keatit71** [comment]
I don't use any narrator

**Comment by mrshmllow** [comment]
Sorry this has been such a broken mod for you, I have found the issue.

**Comment by keatit71** [comment]
Its fine at least you are actively trying to fix the problems
