### ISSUE TITLE
Initializing game Crash in 1.19.2 Forge

### ISSUE THREAD

**Issue by MidasMischief** [mrshmllow/BetterRecipeBook#73]
I'm not quite sure what's causing this crash if it's mod conflict or not but I thought i'd drop this here to see if its on my end or not
[crash-2023-07-11_22.17.24-client.txt](https://github.com/mrshmllow/BetterRecipeBook/files/12023409/crash-2023-07-11_22.17.24-client.txt)

**Comment by mrshmllow** [comment]
1.19.2 is no longer supported
