### ISSUE TITLE
Wrong version dependency for 1.19.2

### ISSUE THREAD

**Issue by Mabra51** [mrshmllow/BetterRecipeBook#74]
The mod version 1.7.2 is tagged as compatible for 1.19.2 but it requires higher versions of Architectury and Cloth Config, which are not for 1.19.2, resulting in crash.

![Sans titre](https://github.com/mrshmllow/BetterRecipeBook/assets/12016338/66a495fc-8142-4cd9-a5a9-017911624d90)

**Comment by mrshmllow** [comment]
1.19 is no longer supported
