### ISSUE TITLE
[Suggestion] Search by mod name

### ISSUE THREAD

**Issue by BLUEChester** [mrshmllow/BetterRecipeBook#78]
If you were able to search items by mod name I would use this to replace EMI instantly. Please add this if you ever get a chance as I hate the cluttered look of JEI and EMI, and would love to be able to use this to replace them.

Thanks!

**Comment by mrshmllow** [comment]
Hello! I dug around in the code and i believe this is vanilla functionality

![image](https://github.com/mrshmllow/BetterRecipeBook/assets/40532058/c58cdc73-af7f-4260-937e-36910c126a02)
