### ISSUE TITLE
Bedrock Edition features

### ISSUE THREAD

**Issue by Madis0** [mrshmllow/BetterRecipeBook#8]
Consider adding options for Bedrock Edition parity features, including (but not limited to):

- [x] Un-merged items (e.g. all kinds of planks are displayed separately)
- [ ] 7x7 vertically scrollable grid
- [ ] One click places all of the item to crafting table
- [ ] Tabs on top (for simplicity, can use existing Java Edition tabs' organization)
- [ ] Creative mode support (recipe book gives free items, survival inventory on the right)

**Comment by mrshmllow** [comment]
Un-merged items is something i want to do, probably a toggle button
