### ISSUE TITLE
Some of the recipes do not work until you unlock the recipe normally - Fabric 1.20.1

### ISSUE THREAD

**Issue by ImpSpy2** [mrshmllow/BetterRecipeBook#83]
Some of the recipes such as the bowl and chest are unlocked and available in the recipe book when you have the required ingredients but selecting them does nothing. Having the instant craft enabled also does not craft them, you are only able to start crafting them from the recipe book once you have already crafted them manually.

Tested on both 1.8 and 1.8.2.

**Comment by TauCubed** [comment]
When you select them does it show a ghost recipe? Or does it just do nothing?

IIRC I didn't implement that code as I figured Minecraft would unlock those recipes when you gained the ingredients. Therefor I just setup a ghost recipe system.

**Comment by ImpSpy2** [comment]
If you don't have the ingredients in your inventory it will show a ghost recipe but if you have the necessary ingredients it will do nothing when you select it.

**Comment by mrshmllow** [comment]
Yeah experiencing this

**Comment by TauCubed** [comment]
I've made a [branch](https://github.com/mrshmllow/BetterRecipeBook/tree/feature-force_place_recipe_option) containing a WIP fix for this. It hasn't been tested much and doesn't currently support batch crafting.

It adds an option to the `new recipes` settings tab that allows you to enable `forcePlaceRecipe` where the client will manually place the selected recipe into the crafting grid.

I might work on this some more later.

**Comment by mrshmllow** [comment]
@TauCubed can you make a PR for that branch just so we can track this

**Comment by TauCubed** [comment]
Done. #86

**Comment by mrshmllow** [comment]
fix coming in 1.10.0 full release
