### ISSUE TITLE
Recipe book disabled

### ISSUE THREAD

**Issue by casualfan0** [mrshmllow/BetterRecipeBook#88]
I cannot find how the book was disabled, nor is there a hot key I could find at all. Like, the book is straight up gone from every crafting thing, my inventory, furnace, brewing, etc. Can I get a little help because I dunno, I didn't see any instructions in the mod description about HOW to disable it so I definitely pressed something to make it disappear. Thanks in advance

**Comment by mrshmllow** [comment]
If your using forge, you will have to edit `enableBook` in `INSTANCE/config/brb.toml` or just delete the file

If not, your using fabric, so go to mod menu / better reicpe book / enable the recipe book

![image](https://github.com/mrshmllow/BetterRecipeBook/assets/40532058/e20f8b9b-602b-43f3-87f5-a7ed967b0c88)
