### ISSUE TITLE
Cant start game with new Beta Fabric version: 1.10.0-rc2 for 1.20.2

### ISSUE THREAD

**Issue by malte9799** [mrshmllow/BetterRecipeBook#89]
Mods: 
![image](https://github.com/mrshmllow/BetterRecipeBook/assets/24914119/67adf025-7df5-4fc7-8539-05c5549fdeab)

Log: https://hastebin.com/share/cifeyuraja.lua

**Comment by mrshmllow** [comment]
Will investigate

**Comment by mrshmllow** [comment]
Delisting rc2 while this is fixed
